### ISSUE TITLE
RTL Suport

### ISSUE THREAD

**Issue by hakhsin** [updivision/material-dashboard-laravel#1]
Hi, is this template compatible with RTL language?

**Comment by Ghitu** [comment]
Hello @hakhsin!

Yes, the Material Dashboard theme has RTL support.
Go to the Demo login page: https://material-dashboard-laravel.creative-tim.com/login
After logging in you can find the RTL support link in the left menu, or you can go to this link: https://material-dashboard-laravel.creative-tim.com/rtl-support

Thank you
