### ISSUE TITLE
Has this been tested with Laravel 7.x?

### ISSUE THREAD

**Issue by ozupey** [updivision/material-dashboard-laravel#18]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Easy installation by following the installation guide using the latest Laravel version.

# Current Behavior

There seem to be several issues and mistakes in the documentation when trying to install this dashboard on the latest Laravel framework version (7.3.0).

1. It seems to depend on laravel/ui, but neither the prerequisites or the installation steps mention installing laravel/ui. Results in `Class 'Laravel\Ui\UiCommand' not found`
2. `php artisan preset material` is an invalid command on Laravel 7.x, it has to be `php artisan ui material`.
3. Register and login are not working. Results in `Target class [App\Http\Controllers\Auth\LoginController] does not exist.` and `Target class [App\Http\Controllers\Auth\RegisterController] does not exist.`

**Comment by ozupey** [comment]
It seems like you already updated `README.md` but forgot to update the official website: https://material-dashboard-laravel.creative-tim.com/docs/getting-started/laravel-setup.html

After following the updated documentation, everything went well. :)

**Comment by teamupdivision** [comment]
Hello, thank you for using our products!
Please check, we've updated the docs.

Thank you
