### ISSUE TITLE
Undefined variable: title

### ISSUE THREAD

**Issue by peyobr** [updivision/material-dashboard-laravel#2]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Defined variable: title

# Current Behavior

Undefined variable: title

# Failure Information (for bugs)

Is $title vs $titlePage a typo? Got "Undefined variable: title"

If not please apoligize me...

**Comment by Ghitu** [comment]
Hello,

$title vs $titlePage is not a typo. The $title variable is used for guest pages and $titlePage is used for authenticated pages.
You must include title in parameters array when you extend layout.app and the page can be accessed by an unauthenticated user.
