### ISSUE TITLE
Form controls select option and file upload 

### ISSUE THREAD

**Issue by raar4ever** [updivision/material-dashboard-laravel#21]
When I copied the form from the site, it did not appear as required , and also file upload input not work , 
I'm working on laravel 7.10 .. 
Thank's  

![select form](https://user-images.githubusercontent.com/6019799/81513281-ff0cdb00-932f-11ea-86f9-e23209e767c6.png)
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hello @raar4ever thank you for using our products.
If you copy pasted code from the PRO version to the FREE installed version on you localhost, of course it will not work.

**Comment by raar4ever** [comment]
Form controls its FREE not PRO

**Comment by teamupdivision** [comment]
Please send us the code where you copied code from?
Where did you exactly copy it, an existing project? Does this project have a css template from Createive Tim?

**Comment by Fabienne94** [comment]
i have te same problem how did you fix it?
