### ISSUE TITLE
How do I change to the dark theme?

### ISSUE THREAD

**Issue by evansbusobozi** [updivision/material-dashboard-laravel#23]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

**Comment by teamupdivision** [comment]
issue i believe was resolved here:
https://github.com/laravel-frontend-presets/material-dashboard/issues/22
