### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sarzali07** [updivision/material-dashboard-laravel#24]
php artisan ui material

   InvalidArgumentException 

  Invalid preset.

  at C:\wamp64\www\waterdistribution\vendor\laravel\ui\src\UiCommand.php:41
    37|             return call_user_func(static::$macros[$this->argument('type')], $this);
    38|         }
    39| 
    40|         if (! in_array($this->argument('type'), ['bootstrap', 'vue', 'react'])) {
  > 41|             throw new InvalidArgumentException('Invalid preset.');
    42|         }
    43| 
    44|         $this->{$this->argument('type')}();
    45| 

  1   C:\wamp64\www\waterdistribution\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:33
      Laravel\Ui\UiCommand::handle()

  2   C:\wamp64\www\waterdistribution\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:33
      call_user_func_array([])

I am getting above error what I can do now??
Regards

**Comment by teamupdivision** [comment]
Hello and thank you for using our products!
Please make sure you follow the install instructions correctly. 

**You need to do this:**
Install this preset via composer require laravel-frontend-presets/material-dashboard. 
No need to register the service provider. Laravel 5.5 & up can auto detect the package.

Thank you

**Comment by dewwis** [comment]
i tried this and worked for me:
composer require laravel/ui
