### ISSUE TITLE
Can only install one of: laravel/framework[v8.1.0, 7.x-dev] error

### ISSUE THREAD

**Issue by isaacdarcilla** [updivision/material-dashboard-laravel#25]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

-  [X] I am running the latest version
-  [X] I checked the documentation and found no answer
-  [X] I checked to make sure that this issue has not already been filed
-  [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Installation successful

# Current Behavior

An error occurred in command `composer require laravel-frontend-presets/material-dashboard` with laravel version `"laravel/framework": "^8.0"`

# Failure Information (for bugs)

Stacktrace

```
  Problem 1
    - Can only install one of: laravel/framework[v8.1.0, 7.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, v8.1.0].
    - Can only install one of: laravel/framework[7.x-dev, v8.1.0].
    - laravel-frontend-presets/material-dashboard v1.1.1 requires laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev].
    - Installation request for laravel-frontend-presets/material-dashboard ^1.1 -> satisfiable by laravel-frontend-presets/material-dashboard[v1.1.1].
    - Installation request for laravel/framework (locked at v8.1.0, required as ^8.0) -> satisfiable by laravel/framework[v8.1.0].

```

Package.json

```json
{
  "name": "laravel/laravel",
  "type": "project",
  "description": "The Laravel Framework.",
  "keywords": ["framework", "laravel"],
  "license": "MIT",
  "require": {
    "php": "^7.3",
    "fideloper/proxy": "^4.2",
    "fruitcake/laravel-cors": "^2.0",
    "guzzlehttp/guzzle": "^7.0.1",
    "laravel/framework": "^8.0",
    "laravel/tinker": "^2.0",
    "laravel/ui": "^3.0"
  },
  "require-dev": {
    "facade/ignition": "^2.3.6",
    "fzaninotto/faker": "^1.9.1",
    "mockery/mockery": "^1.3.1",
    "nunomaduro/collision": "^5.0",
    "phpunit/phpunit": "^9.3"
  },
  "config": {
    "optimize-autoloader": true,
    "preferred-install": "dist",
    "sort-packages": true
  },
  "extra": {
    "laravel": {
      "dont-discover": []
    }
  },
  "autoload": {
    "psr-4": {
      "App\\": "app/",
      "Database\\Factories\\": "database/factories/",
      "Database\\Seeders\\": "database/seeders/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "scripts": {
    "post-autoload-dump": [
      "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
      "@php artisan package:discover --ansi"
    ],
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": ["@php artisan key:generate --ansi"]
  }
}
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Tried to downgrade laravel to version 7, no luck.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

OS: Ubuntu 20.04.1 LTS x86_64

**Comment by teamupdivision** [comment]
Hi @isaacdarcilla 

In the next days, we will update at laravel 8. For downgrade, please delete your actual vendor, composer.lock and modify the composer.json file with requirements for laravel 7 from documentation: https://laravel.com/docs/7.x/installation. Follow the instructions for install your project.

All the best

**Comment by teamupdivision** [comment]
Hi @issacdarcilla,

We release the upgrade for Laravel 8.x.

All the best

**Comment by isaacdarcilla** [comment]
Wow thanks for the update.
