### ISSUE TITLE
Form select

### ISSUE THREAD

**Issue by Fabienne94** [updivision/material-dashboard-laravel#29]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

select box with dropdown arrow inside

# Current Behavior

drop down arrow is below select box

![Screenshot_1](https://user-images.githubusercontent.com/44652856/103544797-eba31700-4ea0-11eb-8415-833d73647300.jpg)

**Comment by teamupdivision** [comment]
Hello @Fabienne94 

The select box is a PRO feature not a FREE one.
Did you get the code from the PRO product demo?

Thank you
