### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by Ibra91** [updivision/material-dashboard-laravel#3]
PS C:\Users\User\Project> **php artisan migrate --seed**

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations and table_type = 'BASE TABLE')

  at C:\Users\Ibrahim\Juntas\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)")
      C:\Users\Ibrahim\Juntas\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:70

  2   PDO::__construct("mysql:host=127.0.0.1;port=3306;dbname=homestead", "homestead", "secret", [])
      C:\Users\Ibrahim\Juntas\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:70

  Please use the argument -v to see more details.

I get this error if i want to fix php artisan migrate --seed. And im also not able to login or register

**Comment by Ghitu** [comment]
Hello, please make sure:
- you configured your .env file with the databse connection information for your server
- that MySQL is running on your server
- the MySQL user 'homestead' has the necessary database rights
Thank you
