### ISSUE TITLE
[Bug] New or changed names of Roles not transffereing through to add or edit user pages

### ISSUE THREAD

**Issue by RodneyMiller** [updivision/material-dashboard-laravel#33]
### Version
Current
### Reproduction link
https://ibb.co/SRjL422
### Operating System
Windows 11
### Device
PC
### Browser & Version
Chrome Version 98.0.4758.102 (Official Build) (64-bit)
### Steps to reproduce
1. Changed the name of the roles
2. Added additional roles
3. The drop-down box doesn't work.
### What is expected?
New or edited roles will appear in the add user or edit user interface.
### What is actually happening?
I have changed the name of some roles and have added some new roles but now it's displaying the first role of the old roles when adding or editing a user account and not the new values.

---

**Comment by RodneyMiller** [comment]
I missed the console log.
[127.0.0.1-1645144908218.log](https://github.com/laravel-frontend-presets/material-dashboard/files/8093291/127.0.0.1-1645144908218.log)

**Comment by teamupdivision** [comment]
Hi @RodneyMiller, 

Thanks for reporting this and for using Creative Tim products.

It looks like this feature is not available for the free version. However, if you’re using the PRO version, we've pushed a fix related to this problem.
You can access it by downloading the product from the downloads section on the Creative Tim website.

Updates are present in the following files:

app/Http/Controllers/RoleController.php
resources/views/roles/index.blade.php
resources/views/users/create.blade.php
resources/views/users/edit.blade.php
routes/web.php

Please let us know if everything worked and if there is any other issue.

All the best,
UPDIVISION Team

**Comment by RodneyMiller** [comment]
works great, thank you

**Comment by teamupdivision** [comment]
Hi @RodneyMiller,

Glad to hear that! Thank you for your confirmation. We will go ahead and close this ticket. If there is anything else we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
