### ISSUE TITLE
Support Laravel 9.*

### ISSUE THREAD

**Issue by apolopena** [updivision/material-dashboard-laravel#34]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Support The latest version of Laravel (9.*)

# Current Behavior

Fails when installed with Laravel 9.*

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by teamupdivision** [comment]
Hi @apolopena,

Thank you for your message and for using Creative Tim products. 

We are expecting to have the update to Laravel 9 in the next weeks. At the moment, we're only waiting for this to be stable and all post-launching fixes to be ready. 

For the moment it supports Laravel 8. Please follow us to get notified when the new releases are available.

Also, please let us know if there is any other info we can help with.

All the best,
UPDIVISION Team

**Comment by RyosukeHashimotoGithub** [comment]
not yet?🙂

**Comment by teamupdivision** [comment]
Hi @apolopena,

As promised, we’re happy to announce that the upgrade to Laravel 9.x is ready now and available on our products. 

Please feel free to contact us if you have any questions or issues.

Best,
UPDIVISION Team
