### ISSUE TITLE
[Feature Request]  use Material Dashboard 2 - v3.0.2 but do'nt support RTL ??

### ISSUE THREAD

**Issue by tayasor** [updivision/material-dashboard-laravel#39]
### What is your enhancement?
i use Material Dashboard 2 - v3.0.2 but do'nt support RTL ??
Although full files and attachments are included IN PROJECT

**Comment by teamupdivision** [comment]
Hello,

Thank you for using Creative TIM products!

The RTL is only used as a visual example, there is no option to set RTL for the whole application. 

Let us know if we can help with anything else.
