### ISSUE TITLE
php artisan migrate --seed

### ISSUE THREAD

**Issue by PanduMA** [updivision/material-dashboard-laravel#4]
![image](https://user-images.githubusercontent.com/36406803/61599839-d3145200-ac56-11e9-8f89-d0050aa0bfa8.png)

Why UsersTableSeeder does not exist. I had follow all the instructions step by step

**Comment by ghost** [comment]
Como você resolveu ?

**Comment by ghost** [comment]
1. Em composer.json , anote a versão atual do Laravel , e altere para ^5.5 .
2. `composer update`
3. Em composer.json marque a versão do laravel para a original .
