### ISSUE TITLE
Can't update to laravel 6.0

### ISSUE THREAD

**Issue by 36108** [updivision/material-dashboard-laravel#6]
This week laravel 6.0 is released. on my project i want to update from 5.8 to 6.0. but i get this error: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel-frontend-presets/material-dashboard v1.0.8
    - Conclusion: don't install laravel-frontend-presets/material-dashboard v1.0.8
    - Conclusion: don't install laravel/framework v6.0.1
    - Conclusion: don't install laravel/framework v6.0.0
    - Installation request for laravel-frontend-presets/material-dashboard (locked at v1.0.8, required as ^1.0) -> satisfiable by laravel-frontend-p
resets/material-dashboard[v1.0.8].
    - Conclusion: don't install laravel/framework 6.x-dev
    - laravel-frontend-presets/material-dashboard v1.0.8 requires laravel/framework ^5.5 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5
.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[6.0.x-dev, 5.6.x-dev].
    - Can only install one of: laravel/framework[6.0.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[6.0.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[6.0.x-dev, 5.5.x-dev].
    - Installation request for laravel/framework ^6.0 -> satisfiable by laravel/framework[6.0.x-dev, 6.x-dev, v6.0.0, v6.0.1].

Installation failed, reverting ./composer.json to its original content.

I am not a master in composer etc so any help would be appreciated.

**Comment by eugentudorache** [comment]
Hello @36108 
The presets are not yet compatible with Laravel 6.
We'll do the compatibility update in the next weeks.

Best
Eugen

**Comment by 36108** [comment]
okay thanks, i truly appreciate your help.
i'll wait for the update.

**Comment by 36108** [comment]
is there more information on when it will be updated?

thanks already

**Comment by teamupdivision** [comment]
Hello, @36108  
We just relaunched all the Laravel projects compatible with the latest version of Laravel 6.x. 
All the best.
